# Generated by Django 6.0 on 2025-12-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
